import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

type FeatureKind = 'markdown' | 'supramark';

interface FeatureManifestEntry {
  kind: FeatureKind;
  description?: string;
  dependsOn?: string[];
  cargoFeatures?: string[];
  tsPackages?: string[];
  renderers?: string[];
  containerNames?: string[];
}

interface FeatureManifest {
  version: number;
  features: Record<string, FeatureManifestEntry>;
}

interface BuildProfile {
  name: string;
  description?: string;
  features: string[];
  targets?: string[];
}

interface ResolvedProfile {
  name: string;
  description?: string;
  targets: string[];
  features: string[];
  cargoFeatures: string[];
  tsPackages: string[];
  renderers: string[];
  containerNames: string[];
}

const root = resolve(import.meta.dir, '..');
const profileArg = process.argv[2] ?? 'full';

const manifest = readJson<FeatureManifest>(resolve(root, 'features.manifest.json'));
const profile = readProfile(profileArg);
const resolved = resolveProfile(manifest, profile);

writeJson(resolve(root, '.supramark-build/profile.json'), resolved);
writeEnv(resolve(root, '.supramark-build/profile.env'), resolved);
writeTsRegistry(resolve(root, 'packages/core/src/generated/features.ts'), resolved);
writeRustRegistry(resolve(root, 'crates/supramark-markdown/src/generated/features.rs'), resolved);

console.log(`[supramark] profile: ${resolved.name}`);
console.log(`[supramark] features: ${resolved.features.join(', ') || '(none)'}`);
console.log(`[supramark] cargo features: ${resolved.cargoFeatures.join(',') || '(none)'}`);
console.log(`[supramark] ts packages: ${resolved.tsPackages.join(', ') || '(none)'}`);

function readProfile(arg: string): BuildProfile {
  const path = arg.endsWith('.json') ? resolve(root, arg) : resolve(root, 'profiles', `${arg}.json`);
  return readJson<BuildProfile>(path);
}

function resolveProfile(manifest: FeatureManifest, profile: BuildProfile): ResolvedProfile {
  const selected = new Set<string>();
  const visiting = new Set<string>();

  const addFeature = (id: string) => {
    if (selected.has(id)) return;

    const entry = manifest.features[id];
    if (!entry) {
      throw new Error(`Unknown feature "${id}" in profile "${profile.name}".`);
    }

    if (visiting.has(id)) {
      throw new Error(`Cyclic feature dependency at "${id}".`);
    }

    visiting.add(id);
    for (const dep of entry.dependsOn ?? []) {
      addFeature(dep);
    }
    visiting.delete(id);
    selected.add(id);
  };

  for (const id of profile.features) {
    addFeature(id);
  }

  const features = [...selected];
  const entries = features.map(id => manifest.features[id]);

  return {
    name: profile.name,
    description: profile.description,
    targets: profile.targets ?? [],
    features,
    cargoFeatures: unique(entries.flatMap(entry => entry.cargoFeatures ?? [])).sort(),
    tsPackages: unique(entries.flatMap(entry => entry.tsPackages ?? [])).sort(),
    renderers: unique(entries.flatMap(entry => entry.renderers ?? [])).sort(),
    containerNames: unique(entries.flatMap(entry => entry.containerNames ?? [])).sort(),
  };
}

function writeTsRegistry(path: string, resolved: ResolvedProfile) {
  const content = `// Generated by scripts/build-profile.ts. Do not edit by hand.
export const buildProfile = ${JSON.stringify(resolved, null, 2)} as const;

export type BuildProfileFeatureId = (typeof buildProfile.features)[number];
export type BuildProfileTarget = (typeof buildProfile.targets)[number];

export function isBuildFeatureEnabled(id: string): boolean {
  return (buildProfile.features as readonly string[]).includes(id);
}

export function isContainerEnabled(name: string): boolean {
  return (buildProfile.containerNames as readonly string[]).includes(name);
}
`;
  writeText(path, content);
}

function writeRustRegistry(path: string, resolved: ResolvedProfile) {
  const features = resolved.features.map(id => `    "${escapeRust(id)}",`).join('\n');
  const cargoFeatures = resolved.cargoFeatures
    .map(id => `    "${escapeRust(id)}",`)
    .join('\n');
  const containerNames = resolved.containerNames
    .map(id => `    "${escapeRust(id)}",`)
    .join('\n');

  const content = `// Generated by scripts/build-profile.ts. Do not edit by hand.
pub const BUILD_PROFILE: &str = "${escapeRust(resolved.name)}";

pub const ENABLED_FEATURES: &[&str] = &[
${features}
];

pub const CARGO_FEATURES: &[&str] = &[
${cargoFeatures}
];

pub const CONTAINER_NAMES: &[&str] = &[
${containerNames}
];
`;
  writeText(path, content);
}

function writeEnv(path: string, resolved: ResolvedProfile) {
  const lines = [
    `SUPRAMARK_PROFILE=${shellQuote(resolved.name)}`,
    `SUPRAMARK_CARGO_FEATURES=${shellQuote(resolved.cargoFeatures.join(','))}`,
    `SUPRAMARK_TARGETS=${shellQuote(resolved.targets.join(','))}`,
  ];
  writeText(path, `${lines.join('\n')}\n`);
}

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, 'utf8')) as T;
}

function writeJson(path: string, value: unknown) {
  writeText(path, `${JSON.stringify(value, null, 2)}\n`);
}

function writeText(path: string, content: string) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

function unique(values: string[]): string[] {
  return [...new Set(values)];
}

function escapeRust(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}
