#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { type discoverFeaturePackages, findFeaturePackageByShortName } from './lib-feature-layout';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.join(__dirname, '..');

const FEATURES = [
  'core-markdown',
  'gfm',
  'math',
  'admonition',
  'definition-list',
  'emoji',
  'footnote',
  'wikilink',
];

const docsDir = path.join(projectRoot, 'docs/features');
fs.mkdirSync(docsDir, { recursive: true });

console.log('🚀 Generating Feature docs...\n');

function generateIndexPage(): string {
  let doc = `# Features\n\n`;
  doc += `Supramark provides a rich set of Feature extensions for enhancing Markdown syntax.\n\n`;
  doc += `## Available Features\n\n`;

  for (const shortName of FEATURES) {
    doc += `- [@supramark/feature-${shortName}](./${shortName})\n`;
  }

  doc += `\n## Usage\n\n`;
  doc += `\`\`\`typescript\n`;
  doc += `import { Supramark } from '@supramark/core';\n`;
  doc += `import { someFeature } from '@supramark/feature-xxx';\n`;
  doc += `\`\`\`\n`;

  return doc;
}

function generateFeatureDoc(
  pkg: ReturnType<typeof discoverFeaturePackages extends (infer T)[] ? T : never>,
  featureName: string,
  featurePath: string
): string {
  const featureContent = fs.readFileSync(featurePath, 'utf-8');

  let doc = `# @supramark/${featureName}\n\n`;

  const descMatch = featureContent.match(/description:\s*['"]([^'"]+)['"]/);
  if (descMatch) {
    doc += `${descMatch[1]}\n\n`;
  }

  doc += `## Installation\n\n`;
  doc += `\`\`\`bash\n`;
  doc += `bun add @supramark/core @supramark/${featureName}\n`;
  doc += `\`\`\`\n\n`;

  const syntaxMatch = featureContent.match(
    /syntax:\s*\{[^}]*ast:\s*\{[^}]*type:\s*['"]([^'"]+)['"]/
  );
  if (syntaxMatch) {
    const astType = syntaxMatch[1];
    doc += `## Syntax\n\n`;
    doc += `Type: \`${astType}\`\n\n`;
  }

  doc += `\n---\n*This document is auto-generated by scripts/doc-gen-features.ts*\n`;
  return doc;
}

const indexContent = generateIndexPage();
fs.writeFileSync(path.join(docsDir, 'index.md'), indexContent);
console.log('✅ Generated features/index.md');

for (const shortName of FEATURES) {
  const pkg = findFeaturePackageByShortName(shortName);

  if (!pkg) {
    console.error(`❌ Generation failed: Feature package ${shortName} not found`);
    continue;
  }

  const featureName = `feature-${shortName}`;
  const featurePath = path.join(pkg.dir, 'src/feature.ts');

  if (!fs.existsSync(featurePath)) {
    console.warn(`  ⚠️  ${shortName}: feature.ts does not exist`);
    continue;
  }

  const docContent = generateFeatureDoc(pkg, featureName, featurePath);
  const outputPath = path.join(docsDir, `${shortName}.md`);
  fs.writeFileSync(outputPath, docContent);
  console.log(`  ✅ Generated features/${shortName}.md`);
}

console.log('\n✅ Feature docs generation complete!');
